version: 1.0.0

steps:
  - name: Install Flutter
    run: |
      git clone https://github.com/flutter/flutter.git -b stable
      export PATH="$PATH:pwd/flutter/bin"

  - name: Get Flutter packages
    run: |
      flutter pub get

  - name: Install CocoaPods
    run: |
      cd ios
      pod install --repo-update
      cd ..

  - name: Build iOS
    run: |
      flutter build ios --release --no-codesign